### ISSUE TITLE
table sizes

### ISSUE THREAD

**Issue by shawking** [shawking/SAFEAPEX#1]
How large do all param tables have to be in order to run SAFEAPEX?

**Comment by LECOMTE-ISADEV** [comment]
To BIND HisAFe and APEX we need a common object storing all data using in APEX. We will call this object PARMTYPE in modparmtype.f90 source code. 
Binding tables is possible but only on fixed size tables. 
In APEX lot of table a dynamically allocated with sizes defined by other parameters read in input files.
We have to get ride of this allocation procedure and replace dynamic tables by fixed sizes tables.

At the moment we have fixed the sizes with :
    	MPS = 60;	// MPS = MAX # PESTICIDES
    	MRO = 45;	// MRO = MAX # YRS CROP ROTATION
    	MNT = 300;	// MNT = MAX # TILLAGE OPERATIONS
    	MNC = 200;	// MNC = MAX # CROPS USED
    	MHD = 10;	// MHD = MAX # ANIMAL HERDS
    	MBS = 0;	       // MBS = MAX # BUY/SELL LIVESTOCK TRANSACTIONS
    	MFT = 4;	        // MFT = MAX # FERTILIZER
    	MPO = 60;	// MPO = MAX # POINT SOURCES
    	MHP = 5;	        // MHP = MAX# HYDROGRAPH POINTS
    	MHX = 720;	// MHX = MAX# DAYS FOR STORM HYDROGRAPH BASE
    	MSA = 1;  	// MSA = MAX# SUBAREAS0

        MSL=12;
        MSO=49;       
        NSM=155; 
        MSC=31;                                                                                                                                                          
        NSH=35;

        MOW = 1;
        NPD = 24;
