### ISSUE TITLE
What is ASOL.SOT ?

### ISSUE THREAD

**Issue by LECOMTE-ISADEV** [shawking/SAFEAPEX#10]
In the MAINPROGRAM I see :          

  IF(ISOL==0)THEN
         .....
  ELSE
                  WRITE(ASOL,'(I8.8)')NBSA(ISA)
                  SOILFILE=ASOL//".SOT"
                  CALL OPENV(KR(14),SOILFILE,0)
  END IF

What is ASOL.DAT used for ?

**Comment by shawking** [comment]
Do you mean ASOL.SOT? 
This looks like a soil output file.  The APEX manual states: 
ISOL =
"0 for normal run
> 0 for runs using .SOT files"

**Comment by LECOMTE-ISADEV** [comment]
are you gonna used this kind of output file ?

**Comment by LECOMTE-ISADEV** [comment]
ok
