### ISSUE TITLE
Organic matter in APEX soil

### ISSUE THREAD

**Issue by LECOMTE-ISADEV** [shawking/SAFEAPEX#4]
In HISAFE we define organic matter for each soil as % of fine soil
This parameter is used to calculate pedotransfert functions as  hydraulic conductivity or Theta
Do you have this parameters in APEX soil description ?

**Comment by shawking** [comment]
I don't see a parameter (in the APEX documentation) linking % fine soil (silt?) and organic matter %

**Comment by LECOMTE-ISADEV** [comment]
Are you gonna be able to get this parameters value for your soil ?

**Comment by shawking** [comment]
I guess asking Javier would be the next action.  Does it sound to you like I understand the parameter's definition?

**Comment by shawking** [comment]
"Organic matter is for the entire horizon. We do not have it by soil fractions." -J.O.

**Comment by LECOMTE-ISADEV** [comment]
can you give me the parameter name for Organic matter please ?

**Comment by shawking** [comment]
"APEX works with organic carbon. It gets organic carbon from the soils file (WOC)"

**Comment by LECOMTE-ISADEV** [comment]
I'm not able to deal with this information, we should ask soil expert to tell us what to do 
Maybe we just have to add Soil Organic Matter parameter for each layer ?

**Comment by LECOMTE-ISADEV** [comment]
We fix the problem by calculating 
organicMatter=WOC*2  (organic carbon)
