### ISSUE TITLE
What is SOIL35K.DAT ?

### ISSUE THREAD

**Issue by LECOMTE-ISADEV** [shawking/SAFEAPEX#9]
In the main porgram I found this :

 IF(ISW==4.OR.ISW==5)THEN
          ADUM='SOIL35K.DAT'
          CALL OPENV(KR(28),ADUM,IDIR)
          READ(KR(28),140)XAV,XDV,XRG,BRNG,NSX
          ALLOCATE(XSP(NSX,5))
		  NSNN=.655*NSX**.493
		  EXNN=.767*NSX**.049
	  	  DO I=1,NSX
			  READ(KR(28),140)(XSP(I,J),J=1,5)
          END DO
		  CLOSE(KR(28))
      END IF

This file is not in the folder I have as an example.... What is it ?

**Comment by shawking** [comment]
Seems like SOIL35K.DAT is an instance of the general SOIL****.DAT formated name.
In the manual I see:
"2.8 THE APEX SOIL LIST FILE (SOIL****.DAT)"
in the example they use SOILCOM.DAT.  SOIL35K.DAT may just be an outdated name.  Should I ask Javier?

**Comment by LECOMTE-ISADEV** [comment]
are you gonna used this kind of file ?
